apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-test-tekon1-gitops
  description: This is GitOps manifest for go-test-tekon1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: go-test-tekon1
    janus-idp.io/tekton: go-test-tekon1 
    backstage.io/kubernetes-id: go-test-tekon1
    backstage.io/kubernetes-namespace: go-test-tekon
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-test-tekon1
