apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-test-tekon1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-test-tekon1 
  name: go-test-tekon1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-test-tekon1 
